const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.scrollto,
		C3.Behaviors.Platform,
		C3.Behaviors.MoveTo,
		C3.Behaviors.solid,
		C3.Behaviors.Bullet,
		C3.Plugins.TiledBg,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Plugins.Text,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Behaviors.MoveTo.Acts.SetMovingAngle,
		C3.Behaviors.Platform.Acts.SetGravity,
		C3.Behaviors.MoveTo.Acts.SetAcceleration,
		C3.Behaviors.MoveTo.Acts.SetMaxSpeed,
		C3.Behaviors.MoveTo.Acts.Stop,
		C3.Plugins.Sprite.Cnds.IsMirrored
	];
};
self.C3_JsPropNameTable = [
	{flash_count: 0},
	{ScrollTo: 0},
	{Platform: 0},
	{MoveTo: 0},
	{player: 0},
	{Solid: 0},
	{ground: 0},
	{Sprite: 0},
	{Bullet: 0},
	{lightBullet: 0},
	{TiledBackground: 0},
	{window: 0},
	{light: 0},
	{light2: 0},
	{light3: 0},
	{light4: 0},
	{beam: 0},
	{beam2: 0},
	{light5: 0},
	{flashbangbox: 0},
	{Keyboard: 0},
	{chain: 0},
	{flashbang: 0},
	{Mouse: 0},
	{Text: 0},
	{Text2: 0},
	{Text3: 0},
	{Text4: 0},
	{Text5: 0},
	{Text6: 0},
	{blueCylinder: 0},
	{mainPowerThing: 0},
	{breakwall: 0},
	{box: 0},
	{breakbox: 0},
	{Sprite2: 0},
	{minigamedoor: 0},
	{Sprite3: 0},
	{minigamespawn: 0},
	{Text7: 0},
	{Text8: 0},
	{Text9: 0},
	{flash: 0},
	{fuzzy: 0},
	{Sprite4: 0},
	{light_blend: 0},
	{breakwallplayer: 0},
	{Text10: 0},
	{bomb: 0},
	{stop: 0},
	{Text11: 0},
	{bombWall: 0},
	{floorNotSeen: 0},
	{glitchTabThing: 0}
];

self.InstanceType = {
	player: class extends self.ISpriteInstance {},
	ground: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	lightBullet: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	window: class extends self.ISpriteInstance {},
	light: class extends self.ISpriteInstance {},
	light2: class extends self.ISpriteInstance {},
	light3: class extends self.ISpriteInstance {},
	light4: class extends self.ISpriteInstance {},
	beam: class extends self.ISpriteInstance {},
	beam2: class extends self.ISpriteInstance {},
	light5: class extends self.ISpriteInstance {},
	flashbangbox: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	chain: class extends self.ISpriteInstance {},
	flashbang: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Text: class extends self.ITextInstance {},
	Text2: class extends self.ITextInstance {},
	Text3: class extends self.ITextInstance {},
	Text4: class extends self.ITextInstance {},
	Text5: class extends self.ITextInstance {},
	Text6: class extends self.ITextInstance {},
	blueCylinder: class extends self.ISpriteInstance {},
	mainPowerThing: class extends self.ISpriteInstance {},
	breakwall: class extends self.ISpriteInstance {},
	box: class extends self.ISpriteInstance {},
	breakbox: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	minigamedoor: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	minigamespawn: class extends self.ISpriteInstance {},
	Text7: class extends self.ITextInstance {},
	Text8: class extends self.ITextInstance {},
	Text9: class extends self.ITextInstance {},
	flash: class extends self.ISpriteInstance {},
	fuzzy: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	light_blend: class extends self.ISpriteInstance {},
	breakwallplayer: class extends self.ISpriteInstance {},
	Text10: class extends self.ITextInstance {},
	bomb: class extends self.ISpriteInstance {},
	stop: class extends self.ISpriteInstance {},
	Text11: class extends self.ITextInstance {},
	bombWall: class extends self.ISpriteInstance {},
	floorNotSeen: class extends self.ISpriteInstance {},
	glitchTabThing: class extends self.ISpriteInstance {}
}